#!/usr/bin/env python3
"""
gazebo.launch.py — Spawns minibot in Gazebo Classic (empty world).

Launches gzserver + gzclient directly (not via gazebo_ros/launch/gazebo.launch.py)
to work around multiple Humble-era bugs:
  1. libgazebo_ros_eol_gui.so crashes gzclient on NVIDIA driver 595.x
     (Camera null pointer assertion in OGRE renderer at startup)
  2. models.gazebosim.org network lookup hangs gzserver without internet
  3. GAZEBO_MODEL_PATH not set → package:// URIs unresolved → robot invisible
  4. gazebo_ros2_control rcl parser chokes on colons in URDF XML comments

Usage:
  ros2 launch minibot gazebo.launch.py [paused:=false]
"""
import os
import re
import subprocess
import tempfile
import yaml
import atexit
from os import environ, pathsep

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (
    DeclareLaunchArgument, ExecuteProcess, TimerAction
)
from launch.substitutions import LaunchConfiguration
from launch.conditions import IfCondition, UnlessCondition
from launch_ros.actions import Node


def generate_launch_description():
    pkg = get_package_share_directory('minibot')
    xacro_file = os.path.join(pkg, 'urdf', 'minibot_urdf.xacro')

    # ── Expand URDF eagerly (avoids gazebo_ros2_control 0.4.x rcl bug) ──
    # gazebo_ros2_control internally calls rcl_parse_arguments with
    # '--param robot_description:=<xml>'. Colons inside XML comments
    # (e.g. "ROS 2: ..." or the xacro autogenerated header with a file path)
    # cause the rcl parser to fail at src/rcl/arguments.c:343.
    # Fix: strip all XML comments before storing in the params YAML.
    urdf_xml = subprocess.check_output(['xacro', xacro_file]).decode('utf-8')
    urdf_xml = re.sub(r'<!--.*?-->', '', urdf_xml, flags=re.DOTALL)

    # Write comment-stripped URDF to a temp YAML params file
    _tmp = tempfile.NamedTemporaryFile(
        mode='w', suffix='_robot_desc.yaml', delete=False
    )
    yaml.dump(
        {'robot_state_publisher': {'ros__parameters': {
            'robot_description': urdf_xml,
            'use_sim_time': True,
        }}},
        _tmp, default_flow_style=False, allow_unicode=True,
    )
    _tmp.flush()
    _tmp.close()
    params_file = _tmp.name
    atexit.register(lambda: os.unlink(params_file) if os.path.exists(params_file) else None)

    # ── Build Gazebo environment dict ─────────────────────────────────
    # share_parent = .../install/minibot/share
    # Gazebo resolves "package://minibot/meshes/X.stl"
    # by searching GAZEBO_MODEL_PATH for a dir named "minibot".
    share_parent = os.path.dirname(pkg)

    model_path = share_parent
    if 'GAZEBO_MODEL_PATH' in environ:
        model_path += pathsep + environ['GAZEBO_MODEL_PATH']

    plugin_path = ''
    if 'GAZEBO_PLUGIN_PATH' in environ:
        plugin_path = environ['GAZEBO_PLUGIN_PATH']

    media_path = share_parent
    if 'GAZEBO_RESOURCE_PATH' in environ:
        media_path += pathsep + environ['GAZEBO_RESOURCE_PATH']

    gz_env = {
        # Mesh + resource resolution
        'GAZEBO_MODEL_PATH':    model_path,
        'GAZEBO_PLUGIN_PATH':   plugin_path,
        'GAZEBO_RESOURCE_PATH': media_path,
        # Disable online model database (hangs without internet)
        'GAZEBO_MODEL_DATABASE_URI': '',
        # Suppress multicast "Network is unreachable" spam
        'GAZEBO_IP':         '127.0.0.1',
        'GAZEBO_MASTER_URI': 'http://127.0.0.1:11345',
        # Fix gzclient Camera null pointer assertion on NVIDIA 595.x:
        # The NVIDIA driver crashes Gazebo Classic's OGRE renderer on startup.
        # LIBGL_ALWAYS_SOFTWARE forces Mesa software rasterizer which is stable.
        # OGRE_RTT_MODE=Copy is an additional safety for OGRE FBO issues.
        'LIBGL_ALWAYS_SOFTWARE': '1',
        'OGRE_RTT_MODE': 'Copy',
    }

    # ── Arguments ─────────────────────────────────────────────────────
    paused_arg = DeclareLaunchArgument(
        'paused', default_value='false',
        description='Start Gazebo paused'
    )

    # ── gzserver ──────────────────────────────────────────────────────
    gazebo_ros_dir = get_package_share_directory('gazebo_ros')
    world = os.path.join(gazebo_ros_dir, 'worlds', 'empty.world')

    gzserver_cmd_base = [
        'gzserver',
        world,
        # ROS factory plugin exposes /spawn_entity service
        '-s', 'libgazebo_ros_init.so',
        '-s', 'libgazebo_ros_factory.so',
        '-s', 'libgazebo_ros_state.so',
    ]

    gzserver_paused = ExecuteProcess(
        condition=IfCondition(LaunchConfiguration('paused')),
        cmd=gzserver_cmd_base + ['-u'],
        output='screen',
        additional_env=gz_env,
    )

    gzserver_running = ExecuteProcess(
        condition=UnlessCondition(LaunchConfiguration('paused')),
        cmd=gzserver_cmd_base,
        output='screen',
        additional_env=gz_env,
    )

    # ── gzclient (WITHOUT libgazebo_ros_eol_gui.so) ───────────────────
    # The EOL GUI plugin crashes gzclient on NVIDIA 595.x with a null
    # Camera pointer assertion.  We simply omit it; the GUI still works.
    gzclient = ExecuteProcess(
        cmd=['gzclient'],
        output='screen',
        additional_env=gz_env,
    )

    # ── robot_state_publisher ─────────────────────────────────────────
    rsp = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        name='robot_state_publisher',
        output='screen',
        parameters=[params_file],
    )

    # ── Spawn robot (delayed 4 s to let gzserver + gzclient settle) ───
    spawn = TimerAction(
        period=4.0,
        actions=[
            Node(
                package='gazebo_ros',
                executable='spawn_entity.py',
                name='spawn_minibot',
                output='screen',
                arguments=[
                    '-topic', 'robot_description',
                    '-entity', 'minibot_urdf',
                    '-z', '0.035',
                ],
            )
        ],
    )

    return LaunchDescription([
        paused_arg,
        gzserver_paused, gzserver_running, gzclient, rsp, spawn,
    ])
